### ISSUE TITLE
Mashup with minecraft

### ISSUE THREAD

**Issue by whaleygeek** [casnortheast/microbit_stub#1]
Very good work. Anyone fancy mashing this together with my Minecraft micro:bit simulation? The visualisations would be much nicer. Button presses could be done by hitting the buttons, as could pin inputs.

https://github.com/whaleygeek/mc_microbit

**Comment by casnortheast** [comment]
I am afraid I am unlikely to be able to do much more work on this for  the time being but I am happy for anyone else to take what I have done for other projects.
